services:
  - type: web
    name: httpsms
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: API_KEY
        sync: false
      - key: DATABASE_PATH
        value: ./sms.db
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
