services:
  - type: web
    name: httpsms
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        value: ./firebase-service-account.json
